export const HOME_CONTENT_TH = `<p><span style="text-decoration: underline;">จุดเด่น</span></p>
<ul>
<li>ข้อมูลลงคะแนนมติสามารถประมวลผลได้อย่างรวดเร็ว มีความถูกต้อง และปลอดภัย</li>
<li>ข้อมูลของผู้ทำการเลือกลงคะแนนมติไม่ถูกเปิดเผล สู่สาธารณะ</li>
<li>ไม่สามารถแก้ไขข้อมูลเพื่อเอื้อประโยชน์แก่ผู้มีส่วนได้ส่วนเสียในเรื่องนั้นๆ</li>
<li>ยากต่อการปลอมแปลงหรือสวมสิทธิ์แทนบุคคลอื่น</li>
<li>มีความโปร่งใสผู้ทำการลงคะแนนมติ สามารถตรวจสอบข้อมูลการโหวตของตนเองย้อนหลังได้</li>
<li>ลดค่าใช้จ่ายในการจัดการลงคะแนนมติ สะดวก สามารถลงคะแนนมติผ่านระบบจากทุกที่ที่เข้าถึงอินเทรอ์เน็ตได้</li>
</ul>`;

export const COOKIE_POLICY_TH = `<h4 style="text-align: center;">นโยบายคุกกี้ (Cookie Policy) <br>ระบบการลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (Blockchain-based e-Voting)</h4>
<hr>
<p>เมื่อท่านได้เข้าสู่ระบบการลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (Blockchain-based e-Voting) ของสำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน) หรือ สพร. ข้อมูลที่เกี่ยวข้องกับการเข้าสู่ระบบของท่านจะถูกบันทึกไว้ในรูปแบบของคุ้กกี้ โดยนโยบายคุกกี้นี้จะอธิบายถึงความหมาย การทำงาน วัตถุประสงค์ รวมถึงการลบ และการปฏิเสธการเก็บคุกกี้ เพื่อความเป็นส่วนตัวของท่านโดยการเข้าสู่ระบบนี้ ถือว่าท่านได้อนุญาตให้ สพร. ใช้คุกกี้ตามนโยบายคุกกี้ที่มีรายละเอียดดังต่อไปนี้</p>
<h5>1. คุกกี้คืออะไร</h5>
<p><strong>คุกกี้ (Cookie) </strong>คือ คือ ไฟล์เล็ก ๆ เพื่อจัดเก็บข้อมูลการเข้าใช้งานเว็บไซต์ เช่น วันเวลา ลิงก์ที่คลิก หน้าที่เข้าชม เงื่อนไขการตั้งค่าต่าง ๆ โดยจะบันทึกลงไปในอุปกรณ์คอมพิวเตอร์ และ/หรือ เครื่องมือสื่อสารที่เข้าใช้งานของท่าน เช่น โน้ตบุ๊ก แท็บเล็ต หรือสมาร์ทโฟน ผ่านทางเว็บเบราว์เซอร์ในขณะที่ท่านเข้าสู่เว็บไซต์ โดยคุกกี้จะไม่ก่อให้เกิดอันตรายต่ออุปกรณ์คอมพิวเตอร์ และ/หรือ เครื่องมือสื่อสารของท่าน ในกรณีดังต่อไปนี้ ข้อมูลส่วนบุคคลของท่านอาจถูกจัดเก็บเพื่อใช้เพิ่มประสบการณ์การใช้งานบริการทางออนไลน์ โดยจะจำเอกลักษณ์ของภาษาและปรับแต่งข้อมูลการใช้งานตามความต้องการของท่าน เป็นการยืนยันคุณลักษณะเฉพาะตัว ข้อมูลความปลอดภัยของท่าน รวมถึงบริการที่ท่านสนใจ นอกจากนี้คุกกี้ยังถูกใช้เพื่อวัดปริมาณการเข้าใช้งานบริการทางออนไลน์ การปรับเปลี่ยนเนื้อหาตามการใช้งานของท่าน โดยพิจารณาจากพฤติกรรมการเข้าใช้งานครั้งก่อน ๆ และ ณ ปัจจุบัน และอาจมีวัตถุประสงค์เพื่อการโฆษณาประชาสัมพันธ์&nbsp;</p>
<p>ทั้งนี้ ท่านสามารถค้นหาข้อมูลเพิ่มเติมเกี่ยวกับคุกกี้ได้ที่ www.allaboutcookies.org</p>
<h5>2. มีการใช้คุกกี้ในลักษณะใด</h5>
<p>สพร. ใช้คุกกี้ เพื่อบันทึกการเข้าเยี่ยมชม การสมัครเข้าใช้งาน และการใช้บริการต่าง ๆ บนเว็บไซต์ของท่าน โดยทำให้ สพร. สามารถจดจำการใช้งานเว็บไซต์ของท่านได้ง่ายขึ้น และข้อมูลเหล่านี้จะถูกนำไป เพื่อปรับปรุงเว็บไซต์ของ สพร.ให้ตรงกับความต้องการของท่านมากยิ่งขึ้น เพื่ออำนวยความสะดวกให้เกิดความรวดเร็วในการใช้งานเว็บไซต์ของท่าน และในบางกรณี สพร. จำเป็นต้องให้บุคคลที่สามช่วยดำเนินการดังกล่าว ซึ่งอาจจะต้องใช้ อินเตอร์เน็ตโปรโตคอลแอดเดรส (IP Address) และคุกกี้เพื่อวิเคราะห์ทางสถิติ ตลอดจนเชื่อมโยงข้อมูล และประมวลผลตามวัตถุประสงค์ในการดำเนินการของ สพร.</p>
<p>คุกกี้ที่ สพร. ใช้ อาจจะแบ่งได้ 2 ประเภทตามการจัดเก็บ ดังนี้</p>
<ol>
<li>คุกกี้ที่มีความจำเป็น (Strictly Necessary Cookies) เป็นคุกกี้ที่จะอยู่ตามระยะเวลาที่กำหนดหรือจนกว่าท่านจะลบออก คุกกี้ประเภทนี้จะช่วยให้เว็บไซต์ของ สพร. จดจำท่านและการตั้งค่าต่าง ๆ ของท่านเมื่อท่านกลับมาใช้บริการเว็บไซต์อีกครั้ง ซึ่งจะช่วยให้ท่านเข้าใช้บริการเว็บไซต์ได้สะดวกรวดเร็วยิ่งขึ้น</li>
<li>คุกกี้เพื่อการใช้งานเว็บไซต์(Functional Cookies) เป็นคุกกี้ที่จะอยู่ชั่วคราวเพื่อจดจำท่านในระหว่างที่ท่านเข้าเยี่ยมชมเว็บไซต์ ของ สพร. เช่น เฝ้าติดตามภาษาที่ท่านได้ตั้งค่าและเลือกใช้ เป็นต้น และจะมีการลบออกจากเครื่องคอมพิวเตอร์หรืออุปกรณ์ของท่าน เมื่อท่านออกจากเว็บไซต์หรือได้ทำการปิดเว็บเบราว์เซอร์&nbsp;</li>
</ol>
<h5>3. ประเภทของคุกกี้</h5>
<p>แบ่งได้ 2 ประเภท ดังนี้</p>
<table style="border-collapse: collapse; width: 99.9638%; height: 214.888px;" border="1"><colgroup><col style="width: 50%;"><col style="width: 50%;"></colgroup>
<tbody>
<tr style="height: 13.3889px;">
<td style="height: 13.3889px; text-align: center;"><strong>ประเภทการใช้งานคุกกี้</strong></td>
<td style="height: 13.3889px; text-align: center;"><strong>วัตถุประสงค์</strong></td>
</tr>
<tr style="height: 89.5556px;">
<td style="height: 89.5556px;">คุกกี้ที่มีความจำเป็น (Strictly Necessary Cookies)</td>
<td style="height: 89.5556px;">- เพื่อให้ท่านสามารถเข้าใช้งานในส่วนต่าง ๆ ของระบบได้&nbsp;<br>- เพื่อใช้ในการลงชื่อเข้าใช้งานและการรับรองความถูกต้อง</td>
</tr>
<tr style="height: 111.944px;">
<td style="height: 111.944px;">คุกกี้เพื่อการใช้งานเว็บไซต์<br>(Functional Cookies)</td>
<td style="height: 111.944px;">ใช้เพื่อรวบรวมข้อมูลการใช้งานและประสิทธิภาพการทำงาน เช่น ใช้สำหรับจดจำตัวเลือกที่ตั้งค่าไว้ เพื่อให้ทราบถึงพฤติกรรมของผู้ใช้งาน การปฏิสัมพันธ์ของผู้ใช้งานในการใช้บริการเว็บไซต์ของ สพร. เป็นต้น</td>
</tr>
</tbody>
</table>
<h5>4. ระบบการลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (Blockchain-based e-Voting) ใช้คุกกี้อะไรบ้าง</h5>
<p>เพื่อให้ท่านได้รับทราบข้อมูลการใช้งานคุกกี้ที่ถูกต้อง ท่านสามารถตรวจสอบการใช้งานคุกกี้ได้<br>ผ่าน Application ที่ท่านใช้งานหรือสามารถตรวจสอบรายละเอียดการใช้งานคุกกี้ได้จากเว็บไซต์ของเจ้าของผลิตภัณฑ์ ทั้งนี้ คุกกี้ที่ สพร. ใช้ แบ่งได้ดังนี้</p>
<table style="border-collapse: collapse; width: 99.9638%; height: 313.444px;" border="1"><colgroup><col style="width: 33.2729%;"><col style="width: 33.2729%;"><col style="width: 33.2729%;"></colgroup>
<tbody>
<tr style="height: 22.3889px;">
<td style="height: 22.3889px; text-align: center;"><strong>ประเภทของคุกกี้</strong></td>
<td style="height: 22.3889px; text-align: center;"><strong>รายละเอียด</strong></td>
<td style="height: 22.3889px; text-align: center;"><strong>ตัวอย่าง</strong></td>
</tr>
<tr style="height: 44.7778px;">
<td style="height: 111.945px;" rowspan="3">คุกกี้ที่มีความจำเป็น(Strictly Necessary Cookies)</td>
<td style="height: 44.7778px;">ใช้สำหรับการจัดเก็บข้อมูลผู้ใช้งานเมื่อเข้าใช้งาน</td>
<td style="height: 44.7778px;">sid</td>
</tr>
<tr style="height: 44.7778px;">
<td style="height: 44.7778px;">ใช้สำหรับการจัดเก็บการตั้งค่าภาษาที่ใช้ในระบบ</td>
<td style="height: 44.7778px;">i18n_redirected</td>
</tr>
<tr style="height: 22.3889px;">
<td style="height: 22.3889px;">ใช้สำหรับแสดงนโยบายคุกกี้</td>
<td style="height: 22.3889px;">cc</td>
</tr>
<tr style="height: 179.111px;">
<td style="height: 179.111px;">คุกกี้เพื่อการใช้งานเว็บไซต์<br>(Functional Cookies)</td>
<td style="height: 179.111px;">ใช้สำหรับจดจำตัวเลือกที่ตั้งค่าไว้ หรือ จดจำบัญชีผู้ใช้งานของท่าน</td>
<td style="height: 179.111px;">1P_JAR, AEC, AUEF, APISID, HSID, NID, S, SAPISID, SID, SIDCC, SSID, __Secure-1PAPISID, __Secure-1PSID, __Secure-1PSIDCC, __Secure-3PAPISID, __Secure-3PSID, __Secure-3PSIDCC, _ga</td>
</tr>
</tbody>
</table>
<h5>5. การจัดการคุกกี้ และการปิดกั้นการใช้งานคุกกี้</h5>
<p>บราวเซอร์ส่วนใหญ่จะมีการตั้งค่าให้มีการยอมรับคุกกี้เป็นค่าเริ่มต้น อย่างไรก็ตาม ท่านสามารถปฏิเสธการใช้งานหรือลบคุกกี้ในหน้าการตั้งค่าของบราวเซอร์ที่ท่านใช้งานอยู่ ทั้งนี้ หากท่านทำการปรับเปลี่ยนการตั้งค่าบราวเซอร์ของท่านอาจส่งผลกระทบต่อรูปแบบและการใช้งานบนหน้าเว็บไซต์ของเราได้ หากท่านประสงค์ที่จะทำการปรับเปลี่ยนการตั้งค่า ท่านสามารถตรวจสอบรายละเอียดเพิ่มเติมได้เว็บไซต์ของผู้พัฒนาบราวเซอร์ต่าง ๆ ดังกล่าว ซึ่ง ณ วันที่จัดทำเอกสารฉบับนี้ เป็นไปตามข้างล่าง</p>
<ul>
<li><strong>Android (Chrome)</strong><br>https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DAndroid&amp;hl=en&amp;oco=1</li>
<li><strong>Apple Safari</strong><br>https://support.apple.com/en-gb/guide/safari/sfri11471/mac</li>
<li><strong>Blackberry</strong><br>https://docs.blackberry.com/content/dam/docs-blackberry-com/release-pdfs/en/device-user-guides/BlackBerry-Classic-Smartphone-10.3.3-User-Guide-en.pdf</li>
<li><strong>Google Chrome</strong><br>https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&amp;hl=en</li>
<li><strong>Microsoft Edge</strong><br>https://support.microsoft.com/en-us/windows/microsoft-edge-browsing-data-and-privacy-bb8174ba-9d73-dcf2-9b4a-c582b4e640dd</li>
<li><strong>Microsoft Internet Explorer</strong><br>https://support.microsoft.com/en-us/topic/delete-and-manage-cookies-168dab11-0753-043d-7c16-ede5947fc64d</li>
<li><strong>Mozilla Firefox</strong><br>https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?redirectslug=enable-and-disable-cookies-website-preferences&amp;redirectlocale=en-US</li>
<li><strong>Opera</strong><br>https://help.opera.com/en/latest/web-preferences/</li>
<li><strong>Iphone or Ipad (Chrome)</strong><br>https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DiOS&amp;hl=en&amp;oco=1</li>
<li><strong>Iphone or Ipad (Safari)&nbsp;</strong><br>https://support.apple.com/en-us/HT201265</li>
</ul>
<p>ทั้งนี้ ทั้งนี้ โปรดทราบว่า หากท่านเลือกที่จะปิดการใช้งานคุกกี้บนเบราว์เซอร์หรืออุปกรณ์ของท่าน อาจส่งผลกระทบกับการทำงานบางส่วนของรระบบการลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (Blockchain-based e-Voting) ที่ไม่สามารถทำงานหรือให้บริการได้เป็นปกติ</p>
<p>สพร. จะไม่รับผิดชอบและ สพร. ไม่ได้มีความเกี่ยวข้องกับเว็บไซต์ รวมทั้งเนื้อหาในเว็บไซต์ต่าง ๆ ที่กล่าวมาข้างบน</p>
<p>สำหรับข้อมูลอื่น ๆ เพิ่มเติมในเรื่องนี้ ท่านสามารถเข้าไปอ่านได้ที่ https://www.aboutcookies.org/how-to-delete-cookies</p>
<h5>6. ติดต่อ สพร.</h5>
<p>หากท่านมีคำถามเกี่ยวกับนโยบายนี้ โปรดติดต่อ สพร.โดยมีรายละเอียด ดังนี้</p>
<p><strong>เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล (Data Protection Officer: DPO)</strong></p>
<ul>
<li>สถานที่ติดต่อ: เลขที่ ๑๐๘ อาคารบางกอกไทยทาวเวอร์ ชั้น ๑๗ ถนนรางน้ำ แขวงถนนพญาไท&nbsp;เขตราชเทวี กรุงเทพมหานคร</li>
<li>ช่องทางการติดต่อ: DGA_pdpa@dga.or.th และ contact@dga.or.th</li>
<li>โทรศัพท์ที่ 02-612-6000</li>
</ul>
<h5>7. การเปลี่ยนแปลงนโยบาย</h5>
<p>นโยบายนี้อาจมีการปรับปรุงให้เหมาะสมและสอดคล้องกับสถานการณ์และตามการให้บริการจริง โดย สพร. จะมีการแจ้งนโยบายที่มีการปรับปรุงใหม่บนระบบการลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน &nbsp;(Blockchain-based e-Voting) ดังนั้น สพร. ขอแนะนำให้ท่านตรวจสอบให้แน่ใจว่าท่านได้เข้าใจการเปลี่ยนแปลงตามข้อกำหนดดังกล่าว</p>`

export const PRIVACY_POLICY_TH = `<p style="margin-bottom: 0cm; text-align: center; line-height: normal;" align="center"><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-font-family: 'Arial Unicode MS'; color: windowtext; mso-style-textoutline-type: none; mso-style-textoutline-outlinestyle-dpiwidth: 0pt; mso-style-textoutline-outlinestyle-linecap: round; mso-style-textoutline-outlinestyle-join: bevel; mso-style-textoutline-outlinestyle-pctmiterlimit: 0%; mso-style-textoutline-outlinestyle-dash: solid; mso-style-textoutline-outlinestyle-align: center; mso-style-textoutline-outlinestyle-compound: simple; mso-no-proof: yes;"> </span><strong><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: windowtext;"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-spacerun: yes;"> </span></span></strong><strong><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: windowtext;">คำประกาศเกี่ยวกับความเป็นส่วนตัว</span></strong><strong><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-fareast-font-family: 'TH SarabunPSK'; color: windowtext;"> (Privacy Notice)</span></strong></p>
<p style="margin-bottom: 0cm; text-align: center; line-height: normal;" align="center"><strong><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-themecolor: text1;">ของ</span></strong><strong><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-fareast-font-family: Prompt; mso-no-proof: yes;">ระบบ</span></strong><strong><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span></strong><strong><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-themecolor: text1;">Blockchain-based e-Voting)</span></strong></p>
<p style="margin-bottom: 0cm; text-align: center; line-height: normal;" align="center"><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: windowtext;">---------------------------------------------------------------------------------------------------------------</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">คำประกาศเกี่ยวกับความเป็นส่วนตัว (&ldquo;ประกาศ&rdquo;) นี้จัดทำขึ้นเพื่อให้ท่านซึ่งเป็นผู้ใช้งาน </span><span lang="TH" style="mso-fareast-font-family: Prompt; mso-bidi-font-family: 'TH SarabunPSK'; mso-no-proof: yes;">ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (ซึ่งต่อไปในประกาศนี้ เรียกว่า &ldquo;กิจกรรมการประมวลผล&rdquo;)ได้ทราบและเข้าใจรูปแบบการเก็บรวบรวม ใช้ และเปิดเผย (&ldquo;ประมวลผล&rdquo;) ข้อมูลส่วนบุคคลที่สำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน) (สพร.) (ซึ่งต่อไปในประกาศนี้ เรียกว่า &ldquo;สพร.&rdquo;) ดำเนินการในฐานะผู้ควบคุมข้อมูลส่วนบุคคล ในข้อมูลส่วนบุคคลที่เก็บรวบรวมจากท่านเพื่อการดำเนินการภายใต้กิจกรรมการประมวลผลนี้</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-spacerun: yes;">&nbsp;</span>ผู้ให้บริการได้ให้บริการ</span><span lang="TH" style="mso-fareast-font-family: Prompt; mso-bidi-font-family: 'TH SarabunPSK'; mso-no-proof: yes;">ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Blockchain-based e-Voting)<strong> </strong><span lang="TH">เพื่อให้เป็นไปตาม พระราชกฤษฎีกาจัดตั้งสำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน) พ.ศ. ๒๕๖๑ มาตรา ๘ กำหนดให้ สพร. ให้บริการส่งเสริมและสนับสนุนการดำเนินงานของหน่วยงานรัฐและหน่วยงานอื่นในการพัฒนารัฐบาลดิจิทัลในการ (๑) ดำเนินการพัฒนา บริหารจัดการและให้บริการโครงสร้างพื้นฐานทางเทคโนโลยีดิจิทัล และระบบการให้บริการหรือแอปพลิเคชันพื้นฐานในส่วนที่เกี่ยวข้องกับรัฐบาลดิจิทัล</span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-spacerun: yes;">&nbsp;</span><span style="letter-spacing: -.3pt;">ทั้งนี้ สพร. เก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของผู้ใช้บริการ ดังนี้</span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><strong><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1; letter-spacing: -.3pt;">&nbsp;</span></strong></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext; mso-themecolor: text1; mso-ansi-font-weight: bold;"><span style="mso-list: Ignore;">๑.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">ฐานในการประมวลผลข้อมูลส่วนบุคคล </span></strong><a name="_Hlk65760631"></a></p>
<p style="text-indent: 14.2pt; mso-layout-grid-align: none; text-autospace: none;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-themecolor: text1; mso-bidi-language: TH;">ผู้ให้บริการ</span><span lang="AR-SA" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">ดำเนินการ</span><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">เก็บรวบรวม</span><span lang="AR-SA" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">ข้อมูลส่วนบุคคลของ</span><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">ผู้ใช้บริการ</span><span lang="AR-SA" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">ภายใต้ฐาน ดังต่อไปนี้</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">๑.๑ ความจำเป็นในการดำเนินงานตามภารกิจสาธารณะหรือการใช้อำนาจรัฐที่ สพร. ได้รับภายใต้ พระราชกฤษฎีกาจัดตั้งสำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน) พ.ศ. ๒๕๖๑ มาตรา ๘ (๗) ศึกษา วิจัย สร้างนวัตกรรม และส่งเสริมและสนับสนุนงานวิชาการ งานวิจัยและนวัตกรรมในการพัฒนารัฐบาลดิจิทัล</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">๑.๒ สพร. ได้รับความยินยอมจากผู้ใช้บริการ (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">Consent)</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๒.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">วัตถุประสงค์และฐานในการประมวลผลข้อมูลส่วนบุคคล </span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">๒.๑</span><span lang="TH" style="font-family: 'Arial Unicode MS',sans-serif; mso-ascii-font-family: 'TH SarabunPSK'; mso-hansi-font-family: 'TH SarabunPSK'; color: red;"> </span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">เพื่อใช้ตรวจสอบ และดำเนินการยืนยันตัวตนผู้เข้าใช้บริการว่ามีสิทธิในการการเข้าใช้ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Blockchain-based e-Voting)</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">๒.๒ เพื่อการให้บริการต่าง ๆ แก่ผู้ใช้บริการ สพร.จำเป็นต้องใช้ข้อมูลส่วนบุคคลเพื่อดำเนินการบันทึกข้อมูลการลงคะแนนเสียง</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">๒.๓ เพื่อการปรับปรุงประสบการณ์การได้รับบริการของท่าน โดย สพร. จะทำความเข้าใจพฤติกรรม และแนวคิดของผู้ใช้บริการผ่านพฤติกรรม วิธีการใช้บริการของผู้ใช้บริการ เพื่อนำไปปรับปรุงและพัฒนาการให้บริการของ สพร. ซึ่งเป็นไปภายใต้ขอบเขตของหน้าที่ตามกฎหมายที่เกี่ยวข้อง</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">๒.๔ เพื่อการรักษาความมั่นคงปลอดภัยของระบบ</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">๒.๕ เพื่อการวิเคราะห์ทางสถิติของการใช้บริการและปรับปรุงประสิทธิภาพการทำงานของระบบ และเพื่อความจำเป็นในการติดต่อประสานงาน การสอบถาม การแจ้งข่าวสาร และการดำเนินการอื่น ที่เกี่ยวข้องกับระบบการลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">Blockchain-based e-Voting)</span></p>
<p style="text-align: justify; text-justify: inter-cluster; line-height: normal;">&nbsp;</p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๓.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>ข้อมูลส่วนบุคคลที่ผู้ให้บริการเก็บรวบรวมและใช้</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 21.3pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>ตามวัตถุประสงค์ดังรายละเอียดในข้อ ๒. ผู้ให้บริการจะเก็บรวบรวมข้อมูลส่วนบุคคลของผู้ใช้บริการ <br>ดังรายการต่อไปนี้</span></p>
<table style="background: black; border-collapse: collapse; mso-table-layout-alt: fixed; border: none; mso-border-alt: solid black 1.0pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0cm 5.4pt 0cm 5.4pt; mso-border-insideh: 1.0pt solid black; mso-border-insidev: 1.0pt solid black;" border="1" width="633" cellspacing="0" cellpadding="0">
<thead>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes; height: 22.6pt;">
<td style="width: 177.2pt; border: solid black 1.0pt; background: white; padding: 0cm 0cm 0cm 0cm; height: 22.6pt;" valign="top" width="236">
<p style="margin: 0cm; text-align: center; text-indent: 0cm; tab-stops: 21.3pt;" align="center"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">รายการข้อมูลส่วนบุคคล</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">/<span lang="TH">ข้อมูลที่จำเป็น</span></span></p>
</td>
<td style="width: 148.85pt; border: solid black 1.0pt; border-left: none; mso-border-left-alt: solid black 1.0pt; background: white; padding: 0cm 5.4pt 0cm 5.4pt; height: 22.6pt;" valign="top" width="198">
<p style="margin: 0cm; text-align: center; text-indent: 0cm;" align="center"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">แหล่ง</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">/<span lang="TH">วิธีการเก็บรวบรวม</span></span></p>
</td>
<td style="width: 148.85pt; border: solid black 1.0pt; border-left: none; mso-border-left-alt: solid black 1.0pt; background: white; padding: 0cm 5.4pt 0cm 5.4pt; height: 22.6pt;" valign="top" width="198">
<p style="margin: 0cm; text-align: center; text-indent: 0cm;" align="center"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">จุดประสงค์ในการใช้ข้อมูล</span></p>
</td>
</tr>
</thead>
<tbody>
<tr style="mso-yfti-irow: 1; height: 49.3pt;">
<td style="width: 177.2pt; border: solid black 1.0pt; border-top: none; mso-border-top-alt: solid black 1.0pt; background: white; padding: 0cm 0cm 0cm 0cm; height: 49.3pt;" valign="top" width="236">
<p style="margin-left: 7.15pt; tab-stops: 21.3pt 49.65pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">ข้อมูลรายละเอียดส่วนตัวของผู้ใช้บริการ เช่น ชื่อ นามสกุล ข้อมูล เกี่ยวกับการให้บริการแก่ผู้ใช้บริการเช่น หน่วยงานที่สังกัด บริการที่ผู้ใช้บริการเลือก เป็นต้น</span></p>
</td>
<td style="width: 148.85pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black 1.0pt; mso-border-left-alt: solid black 1.0pt; background: white; padding: 0cm 5.4pt 0cm 5.4pt; height: 49.3pt;" valign="top" width="198">
<p style="tab-stops: 20.75pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">จัดเก็บข้อมูลผ่านการกรอกแบบ คำขอสมัครใช้บริการ หรือการสมัครใช้บริการออนไลน์หรือเชื่อมโยง จากผู้ให้บริการ (</span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">IDP) <span lang="TH">ภายนอก (เช่น </span>DigitalID ,ThaiD) <span lang="TH">ภายใต้ คำยินยอมของผู้ใช้บริการ</span></span></p>
</td>
<td style="width: 148.85pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black 1.0pt; mso-border-left-alt: solid black 1.0pt; background: white; padding: 0cm 5.4pt 0cm 5.4pt; height: 49.3pt;" valign="top" width="198">
<p style="tab-stops: 20.75pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="AR-SA" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext;">เพื่อดำเนินการใด ๆ ที่เกี่ยวข้องกับการให้บริการแก่ผู้ใช้บริการ</span><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">เช่น เพื่อสร้างบัญชีผู้ใช้บริการ เพื่อการพิสูจน์และยืนยันตัวตน การบันทึกข้อมูลการลงคะแนนเสียง เพื่อสถานะการเป็นผู้ควบคุมการลงคะแนนเสียงและผู้ควบคุมการลงคะแนนเสียงร่วม เป็นต้น</span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 2; mso-yfti-lastrow: yes; height: 49.3pt;">
<td style="width: 177.2pt; border: solid black 1.0pt; border-top: none; mso-border-top-alt: solid black 1.0pt; background: white; padding: 0cm 0cm 0cm 0cm; height: 49.3pt;" valign="top" width="236">
<p style="margin-left: 7.15pt; tab-stops: 21.3pt 49.65pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">ข้อมูลเกี่ยวกับการใช้งานระบบเทคโนโลยีสารสนเทศของ สพร. ประกอบด้วย</span></p>
<p style="margin-left: 7.15pt; tab-stops: 21.3pt 49.65pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">- </span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">IP address <span lang="TH">และรายละเอียดของเว็บเบราว์เซอร์</span></span></p>
<p style="margin-left: 7.15pt; tab-stops: 21.3pt 49.65pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">- ข้อมูลเกี่ยวกับการใช้งานเว็บไซต์ โดยใช้คุกกี้</span></p>
<p style="margin-left: 7.15pt; tab-stops: 21.3pt 49.65pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">- ข้อมูลจราจรทางคอมพิวเตอร์ ตามกฎหมายว่าด้วยการกระทำความผิดทางคอมพิวเตอร์</span></p>
<p style="margin-left: 7.15pt; tab-stops: 21.3pt 49.65pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">- ข้อมูลเกี่ยวกับวิธีการใช้งานระบบ เพื่อการประมวลผลและวิเคราะห์ข้อมูล โดย </span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">Google Analytics</span></p>
</td>
<td style="width: 148.85pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black 1.0pt; mso-border-left-alt: solid black 1.0pt; background: white; padding: 0cm 5.4pt 0cm 5.4pt; height: 49.3pt;" valign="top" width="198">
<p style="tab-stops: 20.75pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="AR-SA" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext;">จัดเก็บพฤติกรรมการใช้งานโดยการใช้เทคโนโลยีตรวจจับหรือติดตามพฤติกรรมการใช้งาน</span><span lang="AR-SA" style="color: red;"><span style="mso-tab-count: 2;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span></span></p>
</td>
<td style="width: 148.85pt; border-top: none; border-left: none; border-bottom: solid black 1.0pt; border-right: solid black 1.0pt; mso-border-top-alt: solid black 1.0pt; mso-border-left-alt: solid black 1.0pt; background: white; padding: 0cm 5.4pt 0cm 5.4pt; height: 49.3pt;" valign="top" width="198">
<p style="tab-stops: 20.75pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">&bull; เพื่อการปรับปรุงประสบการณ์การได้รับบริการ</span></p>
<p style="tab-stops: 20.75pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">&bull; เพื่อการวิเคราะห์ข้อมูล </span></p>
<p style="tab-stops: 20.75pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">&bull; เพื่อการรักษาความปลอดภัย</span></p>
<p style="tab-stops: 20.75pt; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; color: black; mso-color-alt: windowtext; mso-bidi-language: TH;">&bull; เพื่อการควบคุมการป้องกันข้อมูล</span></p>
</td>
</tr>
</tbody>
</table>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;">&nbsp;</p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๔.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>คุกกี้</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 35.45pt; tab-stops: 63.8pt;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">สพร. เก็บรวบรวมและใช้คุกกี้รวมถึงเทคโนโลยีอื่นในลักษณะเดียวกันในเว็บไซต์ที่เกี่ยวข้องกับบริการนี้ หรือบนอุปกรณ์ของท่านตามแต่บริการที่ท่านใช้งาน ทั้งนี้ เพื่อการดำเนินการด้านความปลอดภัยในการให้บริการ และเพื่อให้ท่านซึ่งเป็นผู้ใช้งานได้รับความสะดวกและประสบการณ์ที่ดีในการใช้งานบริการ ของ สพร. และข้อมูลเหล่านี้จะถูกนำไปเพื่อปรับปรุงระบบของ สพร. ให้ตรงกับความต้องการของท่าน มากยิ่งขึ้น โดยท่านสามารถตั้งค่าหรือลบการใช้งานคุกกี้ได้ด้วยตนเองจากการตั้งค่าในเว็บเบราว์เซอร์ (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">Web Browser) <span lang="TH">ของท่าน</span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 0cm; line-height: normal;"><strong><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;">&nbsp;</span></strong></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๕.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">สิทธิตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. ๒๕๖๒</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ท่านมีสิทธิตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. ๒๕๖๒ ดังต่อไปนี้</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 18.0pt;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-tab-count: 2;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๑ สิทธิในการเข้าถึง รับสำเนาข้อมูลส่วนบุคคลของผู้ใช้บริการ รวมถึงขอให้เปิดเผยที่มาของข้อมูลส่วนบุคคลของท่านที่ผู้ให้บริการเก็บรวบรวมโดยไม่ได้รับความยินยอมจากท่าน เว้นแต่กรณีที่ผู้ให้บริการต้องดำเนินการตามกฎหมายหรือคำสั่งศาล หรือกรณีที่การเข้าถึงและรับสำเนาของท่าน จะส่งผลกระทบที่อาจก่อให้เกิดความเสียหายต่อสิทธิและเสรีภาพของบุคคลอื่น</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 18.0pt;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๒ สิทธิในการขอแก้ไขข้อมูลส่วนบุคคลของท่านที่ไม่ถูกต้องหรือไม่ครบถ้วน เพื่อให้มีความถูกต้อง เป็นปัจจุบัน สมบูรณ์ และไม่ก่อให้เกิดความเข้าใจผิด</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 18.0pt;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 16.0pt;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><span lang="TH">๕.๓ สิทธิในการลบหรือทำลายข้อมูลส่วนบุคคลของท่าน โดยท่านมีสิทธิขอให้ผู้ให้บริการ ลบหรือทำลายข้อมูลส่วนบุคคลของท่าน หรือทำให้ข้อมูลส่วนบุคคลของท่านไม่สามารถระบุตัวบุคคลผู้เป็นเจ้าของข้อมูลได้ ทั้งนี้ การใช้สิทธิลบหรือทำลายข้อมูลส่วนบุคคลนี้จะต้องอยู่ภายใต้เงื่อนไขที่กฎหมายกำหนด</span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 18.0pt;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๔ สิทธิในการขอให้ผู้ให้บริการระงับการใช้ข้อมูลส่วนบุคคลของผู้ใช้บริการ ในกรณีหนึ่งกรณีใดดังต่อไปนี้</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 40.5pt 2.0cm;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๔.๑ เมื่ออยู่ในช่วงเวลาที่ผู้ให้บริการได้ตรวจสอบตามคำร้องขอของผู้ใช้บริการเพื่อให้แก้ไขข้อมูลส่วนบุคคลของท่านให้ถูกต้อง สมบูรณ์และเป็นปัจจุบัน</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 40.5pt 2.0cm;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๔.๒ ข้อมูลส่วนบุคคลของท่านถูกเก็บรวบรวม ใช้หรือเปิดเผยโดยมิชอบด้วยกฎหมาย</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 40.5pt 2.0cm;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๔.๓ เมื่อข้อมูลส่วนบุคคลของท่านหมดความจำเป็นในการเก็บรักษาไว้ตามวัตถุประสงค์<span style="letter-spacing: -.2pt;">ที่ผู้ให้บริการได้แจ้งแก่ท่านในการเก็บรวบรวม เว้นแต่ท่านประสงค์ให้ผู้ให้บริการเก็บรักษาข้อมูลนั้น</span>ต่อไปเพื่อประกอบการใช้สิทธิตามกฎหมายของท่าน</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 40.5pt 2.0cm;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๔.๔ เมื่ออยู่ในช่วงเวลาที่ผู้ให้บริการอยู่ระหว่างพิสูจน์ถึงเหตุอันชอบด้วยกฎหมายในการเก็บรวบรวมข้อมูลส่วนบุคคลของท่าน หรือตรวจสอบความจำเป็นในการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของผู้ใช้บริการเพื่อประโยชน์สาธารณะ อันเนื่องมาจากการที่ท่านได้ใช้สิทธิคัดค้านการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของท่าน</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 18.0pt;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๕ สิทธิในการคัดค้านการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของท่าน เว้นแต่กรณีที่ผู้ให้บริการมีเหตุในการปฏิเสธคำขอของผู้ใช้บริการโดยชอบด้วยกฎหมาย (เช่น ผู้ให้บริการสามารถ<br>แสดงให้เห็นว่าการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของผู้ใช้บริการมีเหตุอันชอบด้วยกฎหมาย<br>ยิ่งกว่า หรือเพื่อการก่อตั้งสิทธิเรียกร้องตามกฎหมาย การปฏิบัติตามหรือการใช้สิทธิเรียกร้องทางกฎหมาย หรือเพื่อประโยชน์สาธารณะตามภารกิจของผู้ให้บริการ เป็นต้น)</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 18.0pt;"><span lang="TH" style="font-size: 16.0pt;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>๕.๖ สิทธิในการขอถอนความยินยอม ในกรณีที่ท่านได้ให้ความยินยอมแก่ผู้ให้บริการ ในการเก็บรวบรวม ใช้หรือเปิดเผยข้อมูลส่วนบุคคล ผู้ใช้บริการมีสิทธิถอนความยินยอมเมื่อใดก็ได้ตลอดระยะเวลา<br>ที่ข้อมูลส่วนบุคคลของท่านถูกเก็บรักษาโดยผู้ให้บริการ เว้นแต่มีข้อจำกัดสิทธิโดยกฎหมายหรือเงื่อนไขการใช้บริการให้ผู้ให้บริการจำเป็นต้องเก็บรักษาข้อมูลต่อไป</span></p>
<p style="text-align: justify; text-justify: inter-cluster; tab-stops: 18.0pt;"><span style="font-size: 16.0pt;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><span lang="TH">๕.๗ สิทธิในการขอรับ ส่งหรือโอนข้อมูลส่วนบุคคล โดยผู้ใช้บริการมีสิทธิในการขอรับข้อมูลส่วนบุคคลของท่านจากผู้ให้บริการได้ ในกรณีที่ผู้ให้บริการได้ทำให้ข้อมูลส่วนบุคคลนั้นอยู่ในรูปแบบ<br>ที่สามารถอ่านหรือใช้งานโดยทั่วไปได้ด้วยเครื่องมือหรืออุปกรณ์ที่ทำงานได้โดยอัตโนมัติและสามารถใช้หรือเปิดเผยข้อมูลส่วนบุคคลได้โดยวิธีการอัตโนมัติ รวมถึงอาจขอให้ผู้ให้บริการส่งหรือโอนข้อมูลในรูปแบบดังกล่าวไปยังผู้ควบคุมข้อมูลส่วนบุคคลรายอื่น ทั้งนี้ การใช้สิทธินี้จะต้องอยู่ภายใต้เงื่อนไขตามที่กฎหมายกำหนด</span></span></p>
<p style="text-indent: 35.45pt;"><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๖.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>การส่งหรือโอนข้อมูลส่วนบุคคลไปยังต่างประเทศ </span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 0cm; line-height: normal; background: transparent;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ผู้ให้บริการมีการประมวลผลข้อมูลส่วนบุคคลของท่านบนระบบที่ตั้งอยู่ในประเทศไทย อย่างไรก็ตาม ผู้ให้บริการอาจส่งหรือโอนข้อมูลส่วนบุคคลเพื่อประมวลผลข้ามพื้นที่หรือข้ามประเทศในบางกรณี โดยผู้ให้บริการจะมีการตรวจสอบเสมอเพื่อให้แน่ใจว่าการโอนข้อมูลเป็นไปอย่างปลอดภัย และผู้รับโอนข้อมูลมีมาตรการป้องกันและคุ้มครองข้อมูลที่เป็นไปตามมาตรฐานที่กฎหมายกำหนด รวมทั้งมีการจัดทำสัญญากับบุคคลที่สามที่เกี่ยวข้องในการส่งหรือโอนข้อมูล ทั้งนี้ เพื่อให้มีการปฏิบัติตามมาตรการป้องกันและคุ้มครองข้อมูลส่วนบุคคลตามที่กำหนด</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 0cm; line-height: normal; tab-stops: 21.3pt; background: transparent;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>ทั้งนี้ การส่งหรือโอนข้อมูลส่วนบุคคลดังกล่าวครอบคลุมเฉพาะกรณี เพื่อการส่งหรือโอนหรือ เพื่อไปจัดเก็บชั่วคราว โดยมิได้มีจุดประสงค์ให้แหล่งจัดเก็บ หรือผู้ควบคุมข้อมูลส่วนบุคคล หรือผู้ประมวลผลข้อมูลส่วนบุคคลในต่างประเทศ (ถ้ามี) ทำการเข้าถึงเนื้อหาข้อมูลเพื่อการอื่นใด นอกเหนือจากจุดประสงค์ในการจัดไว้ชั่วคราวเท่านั้น</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 0cm; line-height: normal; tab-stops: 21.3pt; background: transparent;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">&nbsp;</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 0cm; line-height: normal; tab-stops: 21.3pt; background: transparent;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๗.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>ระยะเวลาในการเก็บรักษาข้อมูลส่วนบุคคล</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ผู้ให้บริการเก็บรักษาข้อมูลส่วนบุคคลของ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ท่าน</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"> ในระยะเวลาเท่าที่จำเป็นตามวัตถุประสงค์<br>ในการเก็บรวบรวมข้อมูลส่วนบุคคลนั้น ทั้งนี้ เมื่อพ้นระยะเวลาดังกล่าว ผู้ให้บริการจะดำเนินการดังนี้ <span style="mso-spacerun: yes;">&nbsp;</span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 35.45pt; line-height: normal; tab-stops: 2.0cm;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">- <span lang="TH">ลบ ทำลายเมื่อหมดความจำเป็นในการใช้ข้อมูลส่วนบุคคลนั้น หรือ</span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 35.45pt; line-height: normal; tab-stops: 2.0cm;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">- <span lang="TH">ทำให้ข้อมูลส่วนบุคคลของ</span></span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ท่าน</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">ไม่สามารถระบุตัวตนได้เพื่อการใช้ประโยชน์ด้านอื่น เช่น <br>การวิเคราะห์ทางสถิติ การปรับปรุงประสิทธิภาพการทำงาน หรือประโยชน์สาธารณะที่สำคัญ เป็นต้น</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 35.45pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">อย่างไรก็ดี ในกรณีที่มีข้อพิพาท การใช้สิทธิหรือคดีความอันเกี่ยวข้องกับข้อมูลส่วนบุคคลของผู้ใช้บริการ ผู้ให้บริการขอสงวนสิทธิในการเก็บรักษาข้อมูลนั้นต่อไปจนกว่าข้อพิพาทนั้นจะได้มีคำสั่งหรือคำพิพากษาถึงที่สุด</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 35.45pt; line-height: normal;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๘.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>การรักษาความมั่นคงปลอดภัยข้อมูลส่วนบุคคล</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>เพื่อเป็นการปกป้องคุ้มครองข้อมูลส่วนบุคคลของ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ท่าน</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">ให้มีความมั่นคงปลอดภัยและป้องกันไม่ให้ผู้อื่นที่ไม่มีสิทธิเข้าถึงข้อมูล รวมถึงรักษาความถูกต้องของข้อมูล </span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ท่าน</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">จะต้องไม่เปิดเผยรหัสผ่านให้กับบุคคลภายนอกทราบ หากท่านได้มีการแบ่งปัน หรือเปิดเผยรหัสผ่าน หรือข้อมูลส่วนบุคคลของ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ผู้ใช้งาน</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">ให้กับบุคคลอื่น หรือแม้ว่าในกรณีใด ๆ ที่ท่านไม่สามารถรักษาความลับในรหัสผ่านส่วนตัว หรือไม่สามารถควบคุมการใช้งานของรหัสผ่านของผู้ใช้งานระบบได้ ท่านจะต้องเป็นผู้รับผิดชอบสำหรับการกระทำใด ๆ ที่เกิดขึ้นภายใต้ชื่อหรือบัญชีของผู้ใช้บริการท่าน โดยถือว่าเป็นการกระทำโดยท่านเองและต้องรับผิดตามกฎหมายในฐานะที่ท่านป็นเจ้าของบัญชี</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext; letter-spacing: -.3pt;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>ทั้งนี้ ผู้ให้บริการขอให้ข้อมูลกับ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; letter-spacing: -.3pt;">ท่าน</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext; letter-spacing: -.3pt;">ว่า ปัจจุบันยังไม่มีวิธีการรับส่งข้อมูลทางอิเล็กทรอนิกส์</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">หรือวิธีการจัดเก็บข้อมูลที่สมบูรณ์แบบหรือไม่มีช่องโหว่ที่ไม่สามารถผ่านเข้าไปได้ ประกอบกับอาจมีบุคคลภายนอกที่พยายามดักข้อมูลหรือทำการใด ๆ เพื่อเข้าถึงข้อมูลระหว่างการส่งข้อมูลหรือเข้ามาในระบบของผู้ใช้งานระบบหรือของ ผู้ให้บริการ อย่างไม่มีสิทธิตามกฎหมาย และบุคคลดังกล่าวอาจนำข้อมูลส่วนบุคคลของผู้ใช้งานระบบไปใช้อย่างไม่ถูกต้อง </span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>อย่างไรก็ดี ผู้ให้บริการมีมาตรการในการรักษาความมั่นคงปลอดภัยข้อมูลส่วนบุคคลอย่างเหมาะสม เพื่อป้องกันมิให้ข้อมูลสูญหาย หรือมีการเข้าถึง ทำลาย ใช้ เปลี่ยนแปลง แก้ไข หรือเปิดเผยข้อมูลส่วนบุคคลโดยไม่ได้รับอนุญาต ซึ่งสอดคล้องกับนโยบายความมั่นคงปลอดภัยสารสนเทศทางไซเบอร์ </span><span style="color: black; mso-themecolor: text1;">(Information and Cyber Security Policy) </span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">ของผู้ให้บริการ </span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 21.3pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๙.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>การมีส่วนร่วมของเจ้าของข้อมูลส่วนบุคคล</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ผู้ให้บริการจะเปิดเผยรายละเอียดข้อมูลส่วนบุคคลก็ต่อเมื่อได้รับคำร้องขอจากเจ้าของข้อมูล <br>ผู้สืบสันดาน ผู้แทนโดยชอบธรรม ผู้อนุบาล หรือผู้พิทักษ์ โดยส่งคำร้องขอ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">ผ่าน </span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">DGA Contact Center <span style="mso-spacerun: yes;">&nbsp;</span><span lang="TH"><br>ทางหมายเลขโทรศัพท์ ๐๒-๖๑๒-๖๐๖๐ หรือไปรษณีย์อิเล็กทรอนิกส์ </span>contact@dga.or.th</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ในกรณีที่เจ้าของข้อมูล ผู้สืบสันดาน ผู้แทนโดยชอบธรรม ผู้อนุบาล หรือผู้พิทักษ์มีการคัดค้านการจัดเก็บ ความถูกต้อง หรือการกระทำใด ๆ เช่น การแจ้งดำเนินการปรับปรุงแก้ไขข้อมูลส่วนบุคคล ผู้ให้บริการจะดำเนินการบันทึกหลักฐานคำคัดค้านดังกล่าวไว้เป็นหลักฐานด้วย</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ทั้งนี้ ผู้ให้บริการอาจปฏิเสธสิทธิตามวรรคสองได้ตามกรณีที่กฎหมายกำหนด หรือในกรณีที่ข้อมูล<br>ส่วนบุคคลของผู้ใช้งานระบบถูกทำให้ไม่ปรากฏชื่อหรือสิ่งบอกลักษณะอันสามารถระบุตัวผู้ใช้งานระบบนั้นได้</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 21.3pt; line-height: normal;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๑๐.<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>ความรับผิดชอบของบุคคลซึ่งประมวลผลข้อมูลส่วนบุคคล</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ผู้ให้บริการกำหนดให้เจ้าหน้าที่เฉพาะผู้ที่มีหน้าที่เกี่ยวข้องในการจัดเก็บรวบรวม ใช้ และเปิดเผยข้อมูลส่วนบุคคลของ</span><span lang="TH" style="mso-fareast-font-family: Prompt; mso-bidi-font-family: 'TH SarabunPSK'; mso-no-proof: yes;">ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Blockchain-based e-Voting) <span lang="TH">เท่านั้น ที่จะสามารถเข้าถึงข้อมูลส่วนบุคคลของ</span></span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ผู้ใช้บริการ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">ได้ โดยผู้ให้บริการขอรับรองว่าจะดำเนินการให้เจ้าหน้าที่ดังกล่าวปฏิบัติตามประกาศนี้อย่างเคร่งครัด</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 21.3pt; line-height: normal;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๑๑.<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>การเปลี่ยนแปลงแก้ไขคำประกาศเกี่ยวกับความเป็นส่วนตัว</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ในการปรับปรุงหรือเปลี่ยนแปลงประกาศนี้ ผู้ให้บริการอาจพิจารณาแก้ไขเปลี่ยนแปลงตามที่<br>ผู้ให้บริการเห็นสมควร และจะทำการแจ้งให้</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ผู้ใช้บริการ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">ทราบผ่านทางหน้าเว็บไซต์ หรือผ่าน</span><span lang="TH" style="mso-fareast-font-family: Prompt; mso-bidi-font-family: 'TH SarabunPSK'; mso-no-proof: yes;">ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Blockchain-based e-Voting)<span lang="TH"> หรือช่องทางอื่นที่ผู้ให้บริการเห็นสมควร หรือผ่านทางผู้ดูแลระบบของหน่วยงานต้นสังกัดของผู้ใช้บริการ โดยมีวันที่ของฉบับล่าสุดกำกับอยู่ตอนท้าย ผู้ให้บริการขอแนะนำให้</span></span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ผู้ใช้บริการ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">โปรดตรวจสอบเพื่อรับทราบประกาศฉบับใหม่อย่างสม่ำเสมอ โดยเฉพาะก่อนที่</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ผู้ใช้บริการ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">จ</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">้<span lang="TH">ะเปิดเผยข้อมูลส่วนบุคคลแก่ผู้ให้บริการ</span><span style="mso-spacerun: yes;">&nbsp; </span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>ทั้งนี้ การเข้าใช้</span><span lang="TH" style="mso-fareast-font-family: Prompt; mso-bidi-font-family: 'TH SarabunPSK'; mso-no-proof: yes;">ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Blockchain-based e-Voting)<span lang="TH"> ของ</span></span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ผู้ใช้บริการ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"> ถือเป็นการรับทราบตามข้อตกลงในประกาศนี้ หาก</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK';">ผู้ใช้บริการ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">ระบบไม่เห็นด้วยกับข้อตกลงในประกาศนี้<span style="letter-spacing: -.2pt;"> โปรดหยุดการใช้งาน</span></span><span lang="TH" style="mso-fareast-font-family: Prompt; mso-bidi-font-family: 'TH SarabunPSK'; mso-no-proof: yes;">ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Blockchain-based e-Voting)<span lang="TH"> <span style="letter-spacing: -.2pt;"><span style="mso-spacerun: yes;">&nbsp;</span>หากผู้ใช้บริการยังคงใช้</span>งาน<span style="letter-spacing: -.1pt;">ภายหลังจากที่ประกาศนี้มีการแก้ไขและนำขึ้นประกาศในเว็บไซต์ หรือ</span></span></span><span lang="TH" style="mso-fareast-font-family: Prompt; mso-bidi-font-family: 'TH SarabunPSK'; mso-no-proof: yes;">ระบบ</span><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">การลงคะแนนเสียงทางอิเล็กทรอนิกส์โดยใช้บล็อกเชน (</span><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Blockchain-based e-Voting)<span lang="TH"> แล้ว ให้ถือว่าผู้ใช้บริการได้รับทราบการเปลี่ยนแปลงดังกล่าวเรียบร้อยแล้ว </span></span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">&nbsp;</span></p>
<p style="margin-left: 35.45pt; text-align: justify; text-justify: inter-cluster; text-indent: -21.25pt; line-height: normal; mso-list: l1 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="TH" style="mso-fareast-font-family: 'TH SarabunPSK'; mso-bidi-font-family: 'TH SarabunPSK'; color: windowtext; mso-color-alt: windowtext;"><span style="mso-list: Ignore;">๑๒.<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><!--[endif]--><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;"><span style="mso-tab-count: 1;"> </span>การติดต่อสอบถาม</span></strong><strong><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-color-alt: windowtext;">&nbsp;</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>ผู้ใช้บริการสามารถติดต่อสอบถามเกี่ยวกับประกาศฉบับนี้ได้ที่</span></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 18.0pt; line-height: normal;"><strong><span lang="TH" style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>ผู้ควบคุมข้อมูลส่วนบุคคล (</span></strong><strong><span style="mso-bidi-font-family: 'TH SarabunPSK'; color: black; mso-themecolor: text1;">Data Controller<span lang="TH">)</span></span></strong></p>
<p style="text-indent: 18.0pt; mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>ชื่อ</span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">: <span lang="TH">สำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน)</span></span></p>
<p style="mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>สถานที่ติดต่อ : ชั้น ๑๗ อาคารบางกอกไทยทาวเวอร์ </span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">108</span><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"> ถนนรางน้ำ แขวงถนนพญาไท เขตราชเทวี กรุงเทพฯ ๑๐๔๐๐</span></p>
<p style="mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>ช่องทางการติดต่อ</span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">: <span lang="TH">โทรศัพท์ ๐</span>-<span lang="TH">๒๖๑๒</span>-<span lang="TH">๖๐๖๐</span>, e-mail : </span><a href="mailto:contact@dga.or.th"><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">contact@dga.or.th</span></a><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"> </span></p>
<p style="margin-top: 6.0pt; mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><strong><span lang="AR-SA" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล (</span></strong><strong><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">Data Protection Officer<span lang="AR-SA">: </span>DPO<span lang="AR-SA">)</span></span></strong></p>
<p style="margin-left: 21.3pt; mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>สำนักงานพัฒนารัฐบาลดิจิทัล </span></strong><strong><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">(<span lang="TH">องค์การมหาชน</span>)</span></strong></p>
<p style="text-align: justify; text-justify: inter-cluster; text-indent: 21.3pt; mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>สถานที่ติดต่อ : สำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน) (สพร.) ชั้น ๑๗ อาคารบางกอกไทยทาวเวอร์ ๑๐๘ ถนนรางน้ำ แขวงถนนพญาไท เขตราชเทวี กรุงเทพฯ ๑๐๔๐๐</span></p>
<p style="text-indent: 21.3pt; mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>ช่องทางการติดต่อ :</span><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;"> </span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;">DGA_pdpa@dga.or.th <span style="mso-spacerun: yes;">&nbsp;</span></span></p>
<p style="text-indent: 21.3pt; mso-layout-grid-align: none; text-autospace: none; border: none; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp; </span></span><span lang="TH" style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">เบอร์โทร ๐</span><span style="font-size: 16.0pt; font-family: 'TH SarabunPSK',sans-serif; mso-bidi-language: TH;">-<span lang="TH">๘๐๐๔</span>-<span lang="TH">๕๓๔๒๑</span></span></p>`
