genesis-file="/ibft-network/genesis.json"
# node-private-key-file="/ibft-network/"
host-allowlist=["*"]
min-gas-price=0

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ADMIN","ETH","NET","PERM","IBFT","TXPOOL"]

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# graphql
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# permissions
# permissions-nodes-config-file-enabled=true
# permissions-nodes-config-file="/config/permissions_config.toml"

# bootnodes
bootnodes=["enode://e1f951c28f1514d9049ce6c6e2f8d332b9ed2e43619fc1b230cf7417aaa0e947c5ec4b2414d1ee09e08a9f0954c8804a7f0cb7f1e72d3f680e84f305484a1f3d@209.15.108.160:30303"]


# Discovery at boot is set to a list of static files, but will also discover new nodes should they be added
# static nodes
static-nodes-file="/ibft-network/static-nodes.json"
discovery-enabled=true
